import { RawNews } from '../types/news'
import { NewsAnalysis } from '../types/analysis'

export type ExportFormat = 'markdown' | 'json' | 'txt'

interface ExportData {
  news: RawNews
  analysis: NewsAnalysis
  importance?: number
}

/**
 * 导出服务 - 将新闻报告导出为不同格式
 */
export class ExportService {
  /**
   * 导出为Markdown格式
   */
  static toMarkdown(data: ExportData[], locale: string = 'zh'): string {
    const title = locale === 'zh' ? '# 财经新闻分析报告' : '# Financial News Analysis Report'
    const date = new Date().toLocaleDateString(locale === 'zh' ? 'zh-CN' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
    const subtitle = locale === 'zh'
      ? `**生成时间**: ${date}  \n**新闻数量**: ${data.length}条\n\n---\n\n`
      : `**Generated**: ${date}  \n**News Count**: ${data.length}\n\n---\n\n`

    let content = `${title}\n\n${subtitle}`

    data.forEach((item, index) => {
      const { news, analysis } = item
      const newsTitle = locale === 'en' && analysis.title_en ? analysis.title_en : news.title
      const summary = locale === 'zh' ? analysis.summary_cn : analysis.summary_en
      const direction = locale === 'en' && analysis.market_impact.direction_en
        ? analysis.market_impact.direction_en
        : analysis.market_impact.direction
      const logic = locale === 'en' && analysis.market_impact.logic_en
        ? analysis.market_impact.logic_en
        : analysis.market_impact.logic
      const markets = locale === 'en' && analysis.market_impact.affected_markets_en
        ? analysis.market_impact.affected_markets_en
        : analysis.market_impact.affected_markets

      content += `## ${index + 1}. ${newsTitle}\n\n`
      content += `**${locale === 'zh' ? '来源' : 'Source'}**: ${news.source.toUpperCase()}  \n`
      content += `**${locale === 'zh' ? '时间' : 'Time'}**: ${new Date(news.time).toLocaleString(locale === 'zh' ? 'zh-CN' : 'en-US')}  \n`
      content += `**${locale === 'zh' ? '市场方向' : 'Market Direction'}**: ${direction}  \n`
      content += `**${locale === 'zh' ? '置信度' : 'Confidence'}**: ${(analysis.confidence * 100).toFixed(0)}%\n\n`

      // AI分析
      content += `### ${locale === 'zh' ? 'AI分析' : 'AI Analysis'}\n\n`
      content += `${summary}\n\n`

      // 市场影响
      content += `### ${locale === 'zh' ? '市场影响' : 'Market Impact'}\n\n`
      content += `${logic}\n\n`
      content += `**${locale === 'zh' ? '受影响市场' : 'Affected Markets'}**: ${markets.join(', ')}\n\n`

      // 相关股票
      if (analysis.related_stocks && analysis.related_stocks.length > 0) {
        content += `**${locale === 'zh' ? '相关股票' : 'Related Stocks'}**:\n\n`
        analysis.related_stocks.forEach(stock => {
          content += `- **${stock.symbol}** (${stock.name}) - ${stock.market}\n`
        })
        content += '\n'
      }

      // 原文链接
      if (news.url) {
        content += `[${locale === 'zh' ? '查看原文' : 'Read Original'}](${news.url})\n\n`
      }

      content += '---\n\n'
    })

    // 添加免责声明
    content += locale === 'zh'
      ? '\n\n## 免责声明\n\n本报告由AI自动生成，仅供信息参考，不构成投资建议。投资有风险，决策需谨慎。\n'
      : '\n\n## Disclaimer\n\nThis report is automatically generated by AI for informational purposes only and does not constitute investment advice. Investing involves risks, and decisions should be made cautiously.\n'

    return content
  }

  /**
   * 导出为纯文本格式
   */
  static toText(data: ExportData[], locale: string = 'zh'): string {
    const title = locale === 'zh' ? '财经新闻分析报告' : 'Financial News Analysis Report'
    const date = new Date().toLocaleDateString(locale === 'zh' ? 'zh-CN' : 'en-US')

    let content = `${title}\n${'='.repeat(title.length)}\n\n`
    content += `${locale === 'zh' ? '生成时间' : 'Generated'}: ${date}\n`
    content += `${locale === 'zh' ? '新闻数量' : 'News Count'}: ${data.length}\n\n`
    content += `${'-'.repeat(50)}\n\n`

    data.forEach((item, index) => {
      const { news, analysis } = item
      const newsTitle = locale === 'en' && analysis.title_en ? analysis.title_en : news.title
      const summary = locale === 'zh' ? analysis.summary_cn : analysis.summary_en
      const direction = locale === 'en' && analysis.market_impact.direction_en
        ? analysis.market_impact.direction_en
        : analysis.market_impact.direction

      content += `${index + 1}. ${newsTitle}\n\n`
      content += `${locale === 'zh' ? '来源' : 'Source'}: ${news.source.toUpperCase()}\n`
      content += `${locale === 'zh' ? '方向' : 'Direction'}: ${direction}\n`
      content += `${locale === 'zh' ? '置信度' : 'Confidence'}: ${(analysis.confidence * 100).toFixed(0)}%\n\n`
      content += `${summary}\n\n`

      if (analysis.related_stocks && analysis.related_stocks.length > 0) {
        content += `${locale === 'zh' ? '相关股票' : 'Related Stocks'}: `
        content += analysis.related_stocks.map(s => `${s.symbol}(${s.name})`).join(', ')
        content += '\n\n'
      }

      content += `${'-'.repeat(50)}\n\n`
    })

    return content
  }

  /**
   * 导出为JSON格式
   */
  static toJSON(data: ExportData[]): string {
    const exportData = {
      generated_at: new Date().toISOString(),
      news_count: data.length,
      news: data.map(item => ({
        news: item.news,
        analysis: item.analysis,
        importance: item.importance
      }))
    }

    return JSON.stringify(exportData, null, 2)
  }
}
