import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { RawNews } from '../types/news'
import { NewsAnalysis } from '../types/analysis'

interface ExportData {
  news: RawNews
  analysis: NewsAnalysis
}

/**
 * PDF导出服务
 */
export class PDFExportService {
  /**
   * 生成PDF报告
   */
  static async generatePDF(data: ExportData[], locale: string = 'zh'): Promise<Blob> {
    const doc = new jsPDF()

    // 设置字体（支持中文需要使用特殊字体）
    // 由于中文字体较大，这里使用简单的ASCII标题

    const title = locale === 'zh' ? 'Financial News Analysis Report' : 'Financial News Analysis Report'
    const date = new Date().toLocaleDateString(locale === 'zh' ? 'zh-CN' : 'en-US')

    // 标题
    doc.setFontSize(20)
    doc.text(title, 105, 20, { align: 'center' })

    // 日期和新闻数量
    doc.setFontSize(10)
    doc.text(`Generated: ${date}`, 105, 30, { align: 'center' })
    doc.text(`News Count: ${data.length}`, 105, 35, { align: 'center' })

    let yPosition = 45

    // 遍历每条新闻
    data.forEach((item, index) => {
      const { news, analysis } = item

      // 检查是否需要新页面
      if (yPosition > 250) {
        doc.addPage()
        yPosition = 20
      }

      // 新闻序号和标题
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')

      // 使用英文标题或transliterate中文
      const newsTitle = analysis.title_en || this.transliterateTitle(news.title)
      const truncatedTitle = newsTitle.length > 60 ? newsTitle.substring(0, 60) + '...' : newsTitle
      doc.text(`${index + 1}. ${truncatedTitle}`, 15, yPosition)
      yPosition += 8

      // 基本信息
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.text(`Source: ${news.source.toUpperCase()}`, 15, yPosition)
      yPosition += 5
      doc.text(`Time: ${new Date(news.time).toLocaleString('en-US')}`, 15, yPosition)
      yPosition += 5

      // 市场方向
      const direction = analysis.market_impact.direction_en || analysis.market_impact.direction
      doc.text(`Direction: ${direction}`, 15, yPosition)
      yPosition += 5
      doc.text(`Confidence: ${(analysis.confidence * 100).toFixed(0)}%`, 15, yPosition)
      yPosition += 7

      // 分析摘要
      doc.setFont('helvetica', 'bold')
      doc.text('Analysis:', 15, yPosition)
      yPosition += 5
      doc.setFont('helvetica', 'normal')

      const summary = analysis.summary_en || this.transliterateSummary(analysis.summary_cn)
      const summaryLines = doc.splitTextToSize(summary, 180)
      doc.text(summaryLines, 15, yPosition)
      yPosition += summaryLines.length * 5

      // 相关股票
      if (analysis.related_stocks && analysis.related_stocks.length > 0) {
        yPosition += 3
        doc.setFont('helvetica', 'bold')
        doc.text('Related Stocks:', 15, yPosition)
        yPosition += 5
        doc.setFont('helvetica', 'normal')

        const stocks = analysis.related_stocks.map(s => `${s.symbol} (${s.name})`).join(', ')
        const stockLines = doc.splitTextToSize(stocks, 180)
        doc.text(stockLines, 15, yPosition)
        yPosition += stockLines.length * 5
      }

      // 分隔线
      yPosition += 5
      doc.setDrawColor(200, 200, 200)
      doc.line(15, yPosition, 195, yPosition)
      yPosition += 10
    })

    // 免责声明
    if (yPosition > 250) {
      doc.addPage()
      yPosition = 20
    }

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Disclaimer', 15, yPosition)
    yPosition += 7
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)

    const disclaimer = locale === 'zh'
      ? 'This report is automatically generated by AI for informational purposes only and does not constitute investment advice. Investing involves risks, and decisions should be made cautiously.'
      : 'This report is automatically generated by AI for informational purposes only and does not constitute investment advice. Investing involves risks, and decisions should be made cautiously.'

    const disclaimerLines = doc.splitTextToSize(disclaimer, 180)
    doc.text(disclaimerLines, 15, yPosition)

    // 返回Blob
    return doc.output('blob')
  }

  /**
   * 简单的中文标题转换（提取关键词）
   */
  private static transliterateTitle(title: string): string {
    // 这里只是简单处理，实际应该使用AI翻译的title_en
    return title.substring(0, 100)
  }

  /**
   * 简单的中文摘要转换
   */
  private static transliterateSummary(summary: string): string {
    // 这里只是简单处理，实际应该使用AI翻译的summary_en
    return summary.substring(0, 300)
  }
}
